version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  data: