name: CI/CD

on:
  push:
    branches:
      - develop
    tags:
      - "*"
  workflow_dispatch:
    tags:
      - "*"

jobs:
  build:
    uses: keinou/github-actions/.github/workflows/build-and-push-node-app.yaml@main
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
